# Generated by Django 2.2.9 on 2020-10-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swansoftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('proimg', models.ImageField(upload_to='merchant_app/product')),
            ],
        ),
    ]
