# Generated by Django 2.2.9 on 2020-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swansoftapp', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Select Status'), ('accecpt', 'Accept'), ('reject', 'Reject')], max_length=10),
        ),
    ]
