# Generated by Django 2.2.9 on 2020-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swansoftapp', '0006_auto_20201009_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accecpt', 'Accept'), ('reject', 'Reject')], max_length=10),
        ),
    ]
